########################################
# 由于 GitHub API 限制，最多可以设置 60 个
########################################

links:
  # 我近期动态
  - https://api.github.com/repos/yxksw/ghapi-json-generator/issues?per_page=20
